### ISSUE TITLE
Not listed in Plugins

### ISSUE THREAD

**Issue by gerroon** [CalebJohn/joplin-inline-todo#1]
Hi

The doc says to search for Inline TODOS to install it but I do not see that this is listed in the plugins.

**Comment by CalebJohn** [comment]
Hi @gerroon I've written the readme in anticipation of a full release. If you came here from my post on the forum you'll notice that I said you'll need to build the plugin yourself if you want to beta test. I'll be releasing this plugin for everyone soon.
