### ISSUE TITLE
I am trying to customize your plugin to support some features 

### ISSUE THREAD

**Issue by psfinal9** [CalebJohn/joplin-inline-todo#12]
Hi @CableJohn,

Thanks for your excellent plugin, first of all, to me, inline plugin is one of my favorite feature in Joplin 👍
Additionally, I am customizing inline-todo to support the following features with my hands.

>**1.  Shows only assignee (no folder name) because it is more straight forward to see what is todo for.**
>>because inline todo will be place in any note where folder name (including note name) is irrelevant to that todo
(for me, i am using Joplin as my diary and when some idea hit me, i add todo in my diary so folder/note name doesn't have any meaning to me)
>>but, i will let user can choose shows folder name/note name or not

>**2. Shows "COMPLETED" todo item as well**
>> because sometimes I need to review/check completed todo as well to see what i did & what i missed.

If you think it is good feature, let me submit PR after some testing with my real notes.

of course, if you have any advice, please, let me know that.

thanks!!!

**Comment by psfinal9** [comment]
BTW, 1. and 2 will not be supported in table type summary

**Comment by CalebJohn** [comment]
Hi @psfinal9,

What you say sounds really useful. Thanks for the interest in this plugin! I'd happily accept a PR for this functionality. 

It would be best if you added this as a new [summary formatter](https://github.com/CalebJohn/joplin-inline-todo/tree/master/src/summaryFormatters) (maybe diary.ts). Feel free to copy the plain formatter and customize it how you'd like. For now I'd like to stay away from having too many options for each formatter and stick with having a few custom formatters that fit different use cases. I'd be happy to let you take ownership of the diary formatter and customize it how you see fit.

I have some [instructions here](https://github.com/CalebJohn/joplin-inline-todo/blob/master/src/settings_tables.ts#L6), that should be enough to get you started, if not feel free to ask me any question here!

**Comment by CalebJohn** [comment]
The search with joplin.data.get does only support a single query. For your additions you can add a completed_query and do a second joplin.data.get if the todo_type has a completed_query field.

**Comment by feuermandel** [comment]
Hi @psfinal9 and @CalebJohn 

we use the really well done plugin in a team on shared notebooks. In addition to the option to also display completed tasks, which I would find very useful, I would also like to see an option that only displays tasks from a specific notebook (and all notebooks below it). Especially if I'm sharing my screen in a meeting, I might not want all my open ToDos to be displayed.

But for this I would have to have an option that I don't select generally in the settings, but specifically for a todo summary or do I have a thinking error here?

What do you think about the two functions? Could this also be helpful for other users?

**Comment by psfinal9** [comment]
HI @feuermandel 

Showing COMPLETED todo item is on my works now and i am still trying to implement & test it.
Regarding selectively showing todo items, i think @CableJohn have to comment 😃.

thanks!!!

**Comment by CalebJohn** [comment]
@feuermandel I think it makes sense to have a per-notebook summary. I will need to think about what the UI will be like (how can we mark a note as notebook only). If you have any ideas please let me know in the new issue I created for it #13.

**Comment by CalebJohn** [comment]
Fixed in #16 Thanks for the added features @psfinal9!

**Comment by psfinal9** [comment]
Thanks for your excellent plug-in @CalebJohn
