### ISSUE TITLE
[Feature Request] Per-notebook summary note

### ISSUE THREAD

**Issue by CalebJohn** [CalebJohn/joplin-inline-todo#13]
> Hi @psfinal9 and @CalebJohn 

> we use the really well done plugin in a team on shared notebooks. In addition to the option to also display completed tasks, which I would find very useful, I would also like to see an option that only displays tasks from a specific notebook (and all notebooks below it). Especially if I'm sharing my screen in a meeting, I might not want all my open ToDos to be displayed.

> But for this I would have to have an option that I don't select generally in the settings, but specifically for a todo summary or do I have a thinking error here?

> What do you think about the two functions? Could this also be helpful for other users?

_Originally posted by @feuermandel in https://github.com/CalebJohn/joplin-inline-todo/issues/12#issuecomment-1233732897_

**Comment by CalebJohn** [comment]
@feuermandel I've been chewing on this for awhile and I think the solution will be to add notebook names to the end of the special comment 
example:
```
<!-- inline-todo-plugin project_1 project_2 -->
```

This would include the todos from project_1 and project_2 but nothing else.

Will this work as a solution for your use case?

**Comment by feuermandel** [comment]
@CalebJohn, this seems to be a simple solution for an users. Thank you for this solution. 

Any tip how to use this with notebooks with spaces in their names?

**Comment by CalebJohn** [comment]
> Any tip how to use this with notebooks with spaces in their names?

Hmmm, I overlooked that. The typical solution would be to wrap the notebook name in quotes e.g. "notebook name". But that doesn't seem friendly. 

Maybe it would be better to make it more restrictive. So instead of putting any notebook, you can add notebook-only to limit the Todos to the current notebook (and sub notebooks)
Example
```
<!-- inline-todo-plugin notebook-only -->
```

What do you think?

**Comment by feuermandel** [comment]
Hmm,

I do like the solution to create a ToDo view with only some notebooks. Regardless where these notebooks are located.

But a ‚this-notebook-only‘ makes sense as well.

Can a special comment have multiple lines? Like this

`<!— inline-todo-plugin
- notebook 1
- notebook 2
—>` 

Thank you very much for your time.

**Comment by CalebJohn** [comment]
It could have multiple lines, but I'm worried about how friendly that will be for users. Maybe I'm over thinking, this feature might only really be useful to power users anyway.

Which would be most comfortable for you? Newlines?

**Comment by feuermandel** [comment]
I would appreciate quotes to add notebooks with spaces in their name. As you said, this is the normal way to handle spaces in names.

**Comment by CalebJohn** [comment]
fixed in https://github.com/CalebJohn/joplin-inline-todo/commit/c622db158a8a2329aad5f36088b1cc374c67eea1

@feuermandel I'm release v1.6.0 right now with the notebook filtering added. Please let me know how it works out for you!
