### ISSUE TITLE
How to activate the table view

### ISSUE THREAD

**Issue by morfien101** [CalebJohn/joplin-inline-todo#14]
The instructions show that there is a table view but, there is no indication how to make use of it.

It would be great if the instructions showed how to switch between the table view and summary view. Or at least gave an indication on when either would be used if its dependent on the TODO type.

Am I missing something because I can not see anything related to this in the instructions?

**Comment by CalebJohn** [comment]
The settings are under `Tools -> Options -> Inline TODO` (Windows/Linux) and `Joplin -> Preferences` (macOS). 

![image](https://user-images.githubusercontent.com/2179547/189472558-9a379f34-1781-41d4-81ee-596e5c36893a.png)

The Table View is selected under the "Summary Note Format" dropdown. It is not dependent on the TODO type.
