### ISSUE TITLE
Feature Request:  using existing Todo Summary note instead of always creating a new one

### ISSUE THREAD

**Issue by SeptemberHX** [CalebJohn/joplin-inline-todo#2]
Hello,

Thanks for your hardworking! I like this plugin very much! 👍

Currently, I use Joplin on multiple computers and sync them with the Joplin server. Though I installed this plugin on all my Joplin clients, it needs to create a new Todo Summary on each client even though a note exists with the name Todo Summary.

Once this plugin can reuse the existing Todo Summary note, the users can sync it between all the clients!

**Comment by CalebJohn** [comment]
Maybe you're using an old version of this plugin? It doesn't create notes anymore so what you describe shouldn't be possible. 

Now the plugin will use any note that contains the text `<!-- inline-todo-plugin -->`. If you have multiple notes with this text, please delete all except for one.

**Comment by SeptemberHX** [comment]
Oh. I seems I deleted the text `<!-- inline-todo-plugin -->` before. It works now with the text. Thanks.
